# Site settings
title: ZEROPX
email: zeropx@gmail.com
description: "Entraping mind experiences through visual communication and technology"
baseurl: ""
url: "zeropx.github.io"

# Build settings
markdown: kramdown
permalink: pretty


#
safe: true
lsi: false
